/*!
 * \file fontutils.h
 * \date 2024-12-30
 * \author Alessandro Bridi [ale.bridi15@gmail.com]
 *
 * \brief Common types for libraster: return codes, callbacks, font/glyph descriptors.
 *
 * \details Drawing primitives and font tables are decoupled from the library:
 *     the user provides a single rectangle-fill callback and supplies fonts
 *     produced by the bundled generator. Each font carries its own glyph
 *     lookup function, so character search is a direct function call rather
 *     than a generic data-driven scan.
 */

#ifndef FONTUTILS_H
#define FONTUTILS_H

#include "colors.h"
#include <stdint.h>

/*!
 * \brief Return codes for libraster operations.
 */
enum RasterReturnCode {
    RASTER_RC_OK,           /*!< Operation completed successfully */
    RASTER_RC_ERROR,        /*!< Operation failed */
    RASTER_RC_NULL_POINTER, /*!< A required pointer was NULL */
};

/*!
 * \brief Horizontal text alignment relative to the label position.
 */
enum FontAlign {
    FONT_ALIGN_LEFT,   /*!< Position is the left edge of the rendered text */
    FONT_ALIGN_CENTER, /*!< Position is the horizontal center of the rendered text */
    FONT_ALIGN_RIGHT,  /*!< Position is the right edge of the rendered text */
};

/*!
 * \brief Callback used to fill a rectangle with a single color.
 *
 * \details This is the only drawing primitive the user must implement. The
 *     library uses it both for box backgrounds and for glyph rasterization,
 *     where the alpha channel of \p color carries the coverage value. A
 *     horizontal line is just a rectangle with `h == 1`.
 *
 *     On STM32 this maps naturally to a DMA2D fill; on SDL it maps to
 *     SDL_FillRect; on a software framebuffer it is two nested loops.
 *
 * \param[in] x     Top-left X position of the rectangle, in pixels.
 * \param[in] y     Top-left Y position of the rectangle, in pixels.
 * \param[in] w     Width of the rectangle, in pixels.
 * \param[in] h     Height of the rectangle, in pixels.
 * \param[in] color Fill color in ARGB.
 *
 * \retval RASTER_RC_OK on success.
 * \retval RASTER_RC_ERROR on hardware/driver failure.
 */
typedef enum RasterReturnCode (*raster_draw_rectangle_callback)(uint16_t x, uint16_t y, uint16_t w, uint16_t h, struct Color color);

/*!
 * \brief Callback used to clear the entire framebuffer.
 *
 * \details Optional. When set on a RasterHandler, raster_api_render switches
 *     to full-redraw mode: every box is drawn each frame after a clear. When
 *     unset, only boxes flagged as updated are drawn (partial mode).
 *
 * \retval RASTER_RC_OK on success.
 * \retval RASTER_RC_ERROR on hardware/driver failure.
 */
typedef enum RasterReturnCode (*raster_clear_screen_callback)(void);

/*!
 * \brief Metadata for a single glyph inside a Font.
 */
struct Glyph {
    char character;  /*!< ASCII character represented by this glyph */
    uint32_t offset; /*!< Byte offset of the glyph data inside Font::sdf_data */
    uint16_t size;   /*!< Length of the glyph data in bytes */
    uint16_t width;  /*!< Native pixel width of the glyph */
    uint16_t height; /*!< Native pixel height of the glyph */
};

/*!
 * \brief Per-font glyph lookup callback.
 *
 * \details Generated by the font generator as a switch-case so the compiler
 *     can choose the optimal dispatch (jump table or comparison tree). The
 *     library never iterates the glyph array directly; it always goes
 *     through the function pointer stored in struct Font.
 *
 * \param[in] c Character to look up.
 *
 * \return Pointer to the matching glyph, or NULL if the character is not in
 *     the font.
 */
typedef const struct Glyph *(*font_find_glyph_callback)(char c);

/*!
 * \brief A rasterizable font.
 *
 * \details Fonts are produced by tools/generator.py and live in the user's
 *     project, not in libraster itself. Labels reference a font by pointer,
 *     so the library never embeds specific font tables and any number of
 *     fonts can coexist.
 */
struct Font {
    uint16_t base_size;                  /*!< Native pixel height the glyphs were generated at */
    const uint8_t *sdf_data;             /*!< RLE-compressed SDF data for all glyphs */
    const struct Glyph *glyphs;          /*!< Glyph table, sorted by character */
    uint16_t glyph_count;                /*!< Number of entries in glyphs[] */
    font_find_glyph_callback find_glyph; /*!< Per-font glyph lookup, generated as a switch-case */
};

/*!
 * \brief Look up the glyph for a character in a font.
 *
 * \details Convenience wrapper around \c font->find_glyph. Returns NULL on
 *     malformed inputs so callers can chain it without extra checks.
 *
 * \param[in] font Font to search in. May be NULL.
 * \param[in] c    Character to look up.
 *
 * \return Pointer to the matching glyph, or NULL if \p font is NULL, has no
 *     find function, or the character is not in the font.
 */
const struct Glyph *font_find_glyph(const struct Font *font, char c);

#endif // FONTUTILS_H
