/*!
 * \file font.h
 * \date 2024-12-30
 * \author Alessandro Bridi [ale.bridi15@gmail.com]
 *
 * \brief Font and glyph descriptors.
 *
 * \details Fonts are produced by tools/generator.py and live in the user's
 *     project, not in libraster itself. Each font carries its own glyph
 *     lookup function pointer, so character search is a direct call rather
 *     than a generic data-driven scan.
 */

#ifndef FONT_H
#define FONT_H

#include <stdint.h>

/*!
 * \brief Horizontal text alignment relative to the label position.
 */
enum FontAlignment {
    FONT_ALIGN_LEFT,   /*!< Position is the left edge of the rendered text */
    FONT_ALIGN_CENTER, /*!< Position is the horizontal center of the rendered text */
    FONT_ALIGN_RIGHT,  /*!< Position is the right edge of the rendered text */
};

/*!
 * \brief Metadata for a single glyph inside a Font.
 *
 * \details Glyphs are stored as RLE-compressed SDF coverage data. The actual
 *     bytes live in Font::sdf_data; this struct only describes the slice
 *     belonging to one character.
 */
struct FontGlyph {
    char character;  /*!< Extended-ASCII character represented by this glyph */
    uint32_t offset; /*!< Byte offset of the glyph data inside Font::sdf_data */
    uint16_t size;   /*!< Length of the glyph data in bytes */
    uint16_t width;  /*!< Native pixel width of the glyph */
    uint16_t height; /*!< Native pixel height of the glyph */
};

/*!
 * \brief Per-font glyph lookup callback.
 *
 * \details Generated by the font generator as a switch-case so the compiler
 *     can choose the optimal dispatch (jump table or comparison tree). The
 *     library never iterates the glyph array directly; it always goes
 *     through the function pointer stored in struct Font.
 *
 * \param[in] character Character to look up.
 *
 * \return Pointer to the matching glyph, or NULL if the character is not in
 *     the font.
 */
typedef const struct FontGlyph *(*font_find_glyph_callback)(char character);

/*!
 * \brief A rasterizable font.
 */
struct Font {
    uint16_t base_size;                  /*!< Native pixel height the glyphs were generated at */
    const uint8_t *sdf_data;             /*!< RLE-compressed SDF data for all glyphs */
    const struct FontGlyph *glyphs;      /*!< Glyph table, sorted by character */
    uint16_t glyph_count;                /*!< Number of entries in glyphs[] */
    font_find_glyph_callback find_glyph; /*!< Per-font glyph lookup, generated as a switch-case */
};

#endif // FONT_H
